set(CMAKE_SYSTEM_NAME Darwin)

set(COMPILER_PREFIX "x86_64-apple-darwin13")
set(CMAKE_SYSTEM_PROCESSOR universal)

find_program(CMAKE_C_COMPILER NAMES ${COMPILER_PREFIX}-clang)
find_program(CMAKE_CXX_COMPILER NAMES ${COMPILER_PREFIX}-clang++)
find_program(CMAKE_AR NAMES ${COMPILER_PREFIX}-ar)
find_program(CMAKE_STRIP NAMES ${COMPILER_PREFIX}-strip)
find_program(CMAKE_RANLIB NAMES ${COMPILER_PREFIX}-ranlib)
find_program(CMAKE_LIBTOOL NAMES ${COMPILER_PREFIX}-libtool)
find_program(CMAKE_LINKER ${COMPILER_PREFIX}-clang++)
find_program(PKG_CONFIG_EXECUTABLE ${COMPILER_PREFIX}-pkg-config)

# macports doesn't provide some libraries for OS X <= 10.7
set(CMAKE_OSX_DEPLOYMENT_TARGET 10.8)

# CHANGE THIS to your actual osxcross sdk path -DCMAKE_OSX_SYSROOT=....
file(GLOB CMAKE_OSX_SYSROOT $ENV{HOME}/osxcross/target/SDK/MacOSX10.*.sdk/)

set(CMAKE_FIND_FRAMEWORK FIRST)
set(CMAKE_FIND_APPBUNDLE FIRST)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
